### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/query-service#1]
# Need
- [x] Rough capacity planning
- [x] ETL job Architecture
- [x] Tentative plan on technology choice
- [x] Search API design
- [x] Indexer interface design (tentatively)
- [x] Event Bus (with DSS)
- [ ] ~Rough migration strategy~
... others?

**Comment by MDunitz** [comment]
https://www.lucidchart.com/invitations/accept/29d63295-dc9d-43e5-82ea-7f9e2b7afc49

**Comment by mweiden** [comment]
@MDunitz I like the diagram!
