### ISSUE TITLE
Update system blueprint

### ISSUE THREAD

**Issue by MDunitz** [HumanCellAtlas/query-service#10]
# Need
* As a Developer
* I want a blueprint of how data flows through the system
* so that I can visualize what currently exists/what is planned

# Approach
- [x] use lucid chart to show architecture plans
- [x] update lucid chart to show reality

**Comment by MDunitz** [comment]
https://www.lucidchart.com/invitations/accept/29d63295-dc9d-43e5-82ea-7f9e2b7afc49

**Comment by mweiden** [comment]
Add sync and async read path

**Comment by mweiden** [comment]
@MDunitz add this to the Github developer README.md.
