### ISSUE TITLE
MVP access to internal developers

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/query-service#102]
# Need
User story:
* As a developer for matrix service, data browser, analysis
* I want to query for HCA metadata in the query service
* to answer questions I have about the metadata as it is stored in the DSS.

# Approach

Open up access to internal developers.

TODO: add any gap requirements that arise as we approach the release.

**Comment by GenevieveHaliburton** [comment]
Many internal developers are getting access as a part of the first round UX study.

#122 is a user guide for access to query service MVP via datagrip or api swagger ui, and will be provided to UX study participants
