### ISSUE TITLE
Capacity Planning

### ISSUE THREAD

**Issue by MDunitz** [HumanCellAtlas/query-service#11]
# Need
* As a developer
* I want to predict the systems needs
* and build accordingly

# Approach
- [ ] determine beta use cases
- [ ] determine system needs to support those use cases
- [ ] determine what the estimated load means for cost/computation against the DSS

**Comment by mweiden** [comment]
Aurora and API Gateway+Lambda should theoretically scale, what we need to do is scale test the new infrastructure. Closing this.
