### ISSUE TITLE
Create documentation for query service for UX testing

### ISSUE THREAD

**Issue by GenevieveHaliburton** [HumanCellAtlas/query-service#122]

**Comment by GenevieveHaliburton** [comment]
Query Service User Guide by @MDunitz 

https://docs.google.com/document/d/1ffjwvDxCE-EgQkUtveR1OHy_FNomWNSxYyYxsuEY0io/edit?usp=sharing

**Comment by mweiden** [comment]
@GenevieveHaliburton @MDunitz could you please deduplicate this with https://github.com/HumanCellAtlas/query-service/issues/150
