### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MDunitz** [HumanCellAtlas/query-service#13]
# Need
* As a user of the Query Service
* I want to know how to use it

* As a developer on the Query Service
* I want to know how to develop on it

# Approach
- [ ] examples for users
- [ ] instructions for deployment
- [x] instructions for developing/getting started

**Comment by MDunitz** [comment]
example of a really good open source readme?

**Comment by mweiden** [comment]
@MDunitz part of this is done and the part that isn't done is covered by #122.
