### ISSUE TITLE
MVP user onboarding documentation

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/query-service#150]
## User story

* As a user of the query service
* need a guide with example queries
* so that I can learn how to use the Query Service

## Definition of Done

- [x] Create a `docs` subdirectory with resources compiled from existing google docs and new info
- [x] Description of the layout of the data in the Query Service
- [x] Publish on readthedocs
- [ ] Link from project REAMDE.md and API Documentation

**Comment by kislyuk** [comment]
@MDunitz please update here once the user guide is included in `docs/` and linked from `docs/index.md`.
