### ISSUE TITLE
Distill findings from UX interviews

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/query-service#175]
## Need

Create a report which summarizes the findings of the first interviews with developers.

**Comment by GenevieveHaliburton** [comment]
Raw observations spreadsheet: https://docs.google.com/spreadsheets/d/1I5WZK9-Op06F-f4MKlGLA1Tfq-YkTTtg1LiWJzaSufs/edit#gid=0

Findings deck: https://docs.google.com/presentation/d/1FW9QNz623xVIJVgEsDj9snnM8u9EA8rH1q80PCPEcEg/edit#slide=id.g59a472010c_0_153
