### ISSUE TITLE
Define Q3 Epics

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/query-service#207]
## Need

We need to define the Q3 epics for the Query Service in response to UX feedback, development progress, and emerging needs of the DCP.

## Definition of done

Epics on the query service board, each with:
* A need / set of user stories
* A definition of done
* Demoable criteria
* A t-shirt size estimation

**Comment by kislyuk** [comment]
Epic suggestions:
* Metadata version migration management
* Discoverability of metadata structure (guided query UX)
* Replace DSS ES

**Comment by mweiden** [comment]
Also: @GenevieveHaliburton is working on a problem statement. Problems from the user perspective:
* Metadata fields are represented differently based on point of consumption (compbios)
* It would be simpler and more maintainable to standardize this set of fields once (developers in service of compbios)

**Comment by mweiden** [comment]
Re. the "Discoverability of metadata structure" epic:
* We could nest the listed features in this issue https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/query-service/192
* The items in that issue are a subset of all of the user stories we _could_ fulfill for this epic
