### ISSUE TITLE
Performance Issue - Querying from the top of the graph to get all children takes upwards of 7 minutes

### ISSUE THREAD

**Issue by MDunitz** [HumanCellAtlas/query-service#209]
Possible fix - include project uuid on process_process_join_table. Only run query within a project (no graph should contain data from multiple projects)

**Comment by MDunitz** [comment]
Indexing the processes substantially speeds this up.

**Comment by mweiden** [comment]
The fix for this is complete, but it would be nice to have a performance regression test for this.

**Comment by mweiden** [comment]
Closing this and adding a separate issue for the regression test.
