### ISSUE TITLE
Monitoring 

### ISSUE THREAD

**Issue by MDunitz** [HumanCellAtlas/query-service#21]
# Need / User Story
* As a Query Service maintainer
* I want to easily determine the current status of the service
* so I can easily determine if anything is broken

# Definition of Done
- [ ] use grafana template in the `dcp-monitoring` repository
- [ ] link to dashboard in readme/documentation

# Related docs
* [dcp-community/rfc2](https://github.com/HumanCellAtlas/dcp-community/blob/master/rfcs/text/0002-monitoring-for-production-systems.md)

**Comment by mweiden** [comment]
Pair with me on this!
