### ISSUE TITLE
Update subscription to DSS to only receive data adhering to compatible schemas

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/query-service#218]
This is required in order to receive data that adheres to a schema versions with which query service is compatible.

**Comment by mweiden** [comment]
@maniarathi the query service is schema agnostic with the exception of the `links.json`, metadata file names, metadata file content types, and the `describedBy` metadata field.

Given this, we are choosing _not_ to filter DSS events by schema version range.
