### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by MDunitz** [HumanCellAtlas/query-service#22]
# Need / User Story
* as a maintainer of the Query Service
* I want to be alerted if it is broken
* so I am aware of any issues

# Definition of Done
- [x] create query-service-alerts slack channel
- [x] black-box monitoring
- [ ] white-box monitoring (number of messages in the DLQ, queue length, any alerts on important RDS metrics)

# Related docs

* [dcp-community/rfc2](https://github.com/HumanCellAtlas/dcp-community/blob/master/rfcs/text/0002-monitoring-for-production-systems.md)

**Comment by mweiden** [comment]
Pair with me on this!
