### ISSUE TITLE
Error Using Sample Queries: Integration

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/query-service#242]
I was browsing `https://query.integration.data.humancellatlas.org/` and i noticed that the sample queries are not running, I see the following as the query results for all of the samples:

```
ERROR:  relation "project" does not exist
LINE 5: FROM project AS p,
```

**Comment by amarjandu** [comment]
It appears the error might be intermittent, i tested shortly after submitting and it was working fine.

**Comment by mweiden** [comment]
@MDunitz we just need to run the ETL in integration to fix this.
