### ISSUE TITLE
Query Builder UI bug - bad query gets stuck 

### ISSUE THREAD

**Issue by GenevieveHaliburton** [HumanCellAtlas/query-service#263]
When using Query Editor in https://query.staging.data.humancellatlas.org/, I submitted a query with incorrect syntax. 
```
SELECT count(distinct (body->‘project_core’->>‘project_title’) )
FROM files
where dcp_schema_type_name = ‘project’;
```

and got this error returned in the query editor window:
```
ERROR:  column "‘project_core’" does not exist
LINE 2: SELECT count(distinct (body->‘project_core’->>‘project_title...
```

I then tried correcting the syntax and resubmitting a query, but continued to get the same error message. As a sanity check, I then tried submitting this query:
```select * from files limit 10;```

and once again got the error:
```
ERROR:  column "‘project_core’" does not exist
LINE 2: SELECT count(distinct (body->‘project_core’->>‘project_title...
```

I then tried closing and reopening the query editor window, opening a new query editor window, and opening a new query editor window in incognito browser, and the same error continued to be returned.

when i tried again >3 hours after the error, i was able to open a fresh query editor window in https://query.staging.data.humancellatlas.org/, and successfully submit `select * from files limit 10`. I then once again triggered the error with 
```
SELECT count(distinct (body->‘project_core’->>‘project_title’) )
FROM files
where dcp_schema_type_name = ‘project’;
```
where once again the same error message returns regardless of what query i try.

**Comment by GenevieveHaliburton** [comment]
in case it matters, i believe the error in the first query was using `‘` style single quotes rather than `'` style single quotes

**Comment by kislyuk** [comment]
@GenevieveHaliburton this was fixed, please try again.
