### ISSUE TITLE
Initial feedback on SQL/jsonb UX

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/query-service#35]
## Need

Now that real data is loaded into the RDS, we should hold an early feedback round (before API completion) on the language and table schema design with a small set of bioinformaticians and app developers. This could inform future schema design and technology choices.

## Approach

- [ ] Gather 3-5 bioinformaticians and app developers.
- [ ] Send them and require reading of the postgres jsonb syntax and Query Service table structure.
- [ ] Ask them to complete a small set of defined queries. Examples:
    1. Query for the UUIDS of all the bundles in the Tabula Muris dataset
    1. Across all projects, count the number of male and female donors
    1. ...
- [ ] Ask them to issue three or four queries from their research projects against the dataset
- [ ] Have respondents complete a short diary entry on their experiences with the system
    1. What parts of the system were useful?
    1. Could you answer important research questions that you couldn't otherwise?
    1. What could be improved?
    1. What were the pros and cons of the schema design from your perspective?
    1. ...

**Comment by GenevieveHaliburton** [comment]
closing as this is superseded by larger block of Query Service UX Study work, see https://docs.google.com/document/d/1GkHRB5Tf1QpD-MEbP1gni2fetIndeV50NA73aIt-U-s/edit?usp=sharing
