### ISSUE TITLE
UX Study #1: query language and core use cases

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/query-service#4]
# Need
For the query service to reach MVP we better UX understanding in two areas:

## 1. Query language usability
As a developer, I need to know if users more easily use SQL than ElasticSearch for finding data of interest.

## 2. Core search use cases

As a developer, I need to know the core search use cases for:
- Primary data/metadata
- Secondary data/metadata
- Matrix data/metadata

These core search use cases will depend on the type of user using the system. Key user types that we intend to serve:
- Researcher with a keyboard
- DCP Developer or advanced analysis portal developer
- Wrangler

# Approach
Work with @GenevieveHaliburton to evaluate the UX of the query language and API.

Update: research plan here: https://docs.google.com/document/d/1GkHRB5Tf1QpD-MEbP1gni2fetIndeV50NA73aIt-U-s/edit

**Comment by GenevieveHaliburton** [comment]
Presentation of findings:
https://docs.google.com/presentation/d/1BZFZ4qxPbOLnqegEklG6i-KRRfaN4-jJ6MQB6y9N1Uc/edit?usp=sharing
