### ISSUE TITLE
Publish a v0 specification of the Query Service

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/query-service#50]
## Need

Now that we've completed some early experiments on how the Query Service should be designed, we should publish a v0 spec of what the design should be.

This specification can, of course, change based on further UX and performance evaluations.

**Comment by MDunitz** [comment]
https://docs.google.com/document/d/1YGKDj83dXGiF9rHog6KoTn5YSGL41cS95K9uAtm1308/edit

**Comment by MDunitz** [comment]
v0 is done, will need to update for refactor
