### ISSUE TITLE
Create elasticsearch vs. postgres UX worksheet

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/query-service#51]
## Need

For product development of the query service, we have real-world users of data repositories try to complete queries in each query language and report on their experience with each.

The task in this ticket is to create a worksheet for participants in the UX study with the queries and some questions for us to learn about their experience.

**Comment by GenevieveHaliburton** [comment]
In person interview template https://docs.google.com/document/d/14fTw91U1xmlmNzimI5j2V9gppr0ISINVBVG0-15MYDg/edit?usp=sharing

Diary study template https://docs.google.com/document/d/1M3z_SS3mtmtDOggUuUzTXqdvee52l56_sd0DWwLZHoQ/edit?usp=sharing
