### ISSUE TITLE
Identify first UX study users

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/query-service#67]
## Need

For our first UX study on whether users prefer the UX of postgres vs elasticsearch, we need a pool of test users.

## Approach

We can start small,
- [ ] Get a list of volunteers, perhaps 4-7 people; probably focus on RFA2 grantees
- [ ] Get a sense for what kinds of questions they would want to ask of the data

**Comment by GenevieveHaliburton** [comment]
Round 1 UX Study participants:

Wranglers: Clay Fischer, Will Sullivan, Chris Villareal, Matthew Green
Browser: Trevor Heathorn, Dave Rogers, Hannes Schmidt
Matrix: Marcus Kinsella, Calvin Nhieu

Study plan: https://docs.google.com/document/d/1GkHRB5Tf1QpD-MEbP1gni2fetIndeV50NA73aIt-U-s/edit?usp=sharing

Links to all study docs in the study plan
